package com.csidigital.shared.enumeration;

public enum InterviewType {
    BEHAVIORAL_INTERVIEW,TECHNICAL_INTERVIEW,CASE_STUDY_INTERVIEW,HUMAN_RESOURCE_INTERVIEW,ONLINE_TEST,ON_SITE_TEST,
    PANEL_INTERVIEW,GROUP_INTERVIEW,PHONE_INTERVIEW,IN_PERSON
    ,
}
